apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
  annotations:
    auto-ingress: "/aaa"
spec:
  selector:
    app: my-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

